routeEnhancers:
  SearchDetailsRoute:
    type: Extbase
    limitToPages: [38]
    extension: LisztCommon
    plugin: SearchDetails
    routes:
      - routePath: '/{documentId}'
        _controller: 'Search::details'
